In [37]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 3.6013e-43, 4.1575e+21],
        [5.3829e+22, 2.0432e+20, 1.0478e+21],
        [5.3370e-08, 2.7149e-06, 1.3591e+22],
        [5.4882e-05, 1.3352e-08, 2.6728e+23],
        [2.0990e-07, 1.7248e-07, 6.7655e+22]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.0995, 0.4038, 0.0737],
        [0.1804, 0.7732, 0.0054],
        [0.7970, 0.7411, 0.1781],
        [0.6394, 0.8339, 0.7171],
        [0.1307, 0.7281, 0.4060]])


In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.6936,  0.2647,  0.1075],
        [ 0.0467, -1.6168,  0.9453],
        [ 1.0507, -1.4575, -1.6169],
        [ 2.1723,  0.4428, -0.0500],
        [ 1.5633, -1.2441, -0.0877]])


In [15]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

In [16]:
print(x,y,z)

tensor([[ 1.4580,  0.0788, -0.6279, -0.2052],
        [ 0.8997,  0.3987,  0.6681, -0.1813],
        [ 0.5268,  1.2149,  0.0928, -0.2646],
        [ 1.5346,  0.4540,  0.3727, -0.8818]]) tensor([ 1.4580,  0.0788, -0.6279, -0.2052,  0.8997,  0.3987,  0.6681, -0.1813,
         0.5268,  1.2149,  0.0928, -0.2646,  1.5346,  0.4540,  0.3727, -0.8818]) tensor([[ 1.4580,  0.0788, -0.6279, -0.2052,  0.8997,  0.3987,  0.6681, -0.1813],
        [ 0.5268,  1.2149,  0.0928, -0.2646,  1.5346,  0.4540,  0.3727, -0.8818]])


In [17]:
x.numpy()

array([[ 1.4580071 ,  0.07881697, -0.62793136, -0.20522878],
       [ 0.89971584,  0.39865273,  0.66814   , -0.18131295],
       [ 0.5267544 ,  1.2149426 ,  0.09275827, -0.26456693],
       [ 1.5345657 ,  0.45396456,  0.37270525, -0.88183314]],
      dtype=float32)

In [85]:
x = torch.ones(2, 2, requires_grad=True)
two = torch.tensor([2.], requires_grad=True)
y = x + two
print(y, y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x123712b90>


In [86]:
z = y * y * 3
y.requires_grad_(True)
z.requires_grad_(True)
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [74]:
a = torch.randn(2,2)
a = ((a * 3) / (a-1))

a.requires_grad_(True)

print(a)

tensor([[-3.9387e+03, -1.3157e-01],
        [ 7.2128e+00, -1.1679e+01]], requires_grad=True)


In [87]:
out.backward()
print(x.grad, y.grad, z.grad, two.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]]) None None tensor([18.])


In [32]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

tensor([-314.5203,  123.1389, 1560.8809], grad_fn=<MulBackward0>)


In [34]:
y.data.norm()

tensor(1597.0082)

In [35]:
y.data

tensor([-314.5203,  123.1389, 1560.8809])

In [63]:
x = torch.randn(3, requires_grad=True)

y = x * 2
y.requires_grad_(True)
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-1315.4301,   -51.5920,  -121.1032], grad_fn=<MulBackward0>)


In [62]:
v = torch.tensor([.1,1,.0001])
y.backward(v)

In [48]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [51]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        print(x.size())
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [52]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

torch.Size([1, 16, 6, 6])
tensor([[-0.0680,  0.0659, -0.0312, -0.0723,  0.0846,  0.0389,  0.0479, -0.0341,
          0.0756, -0.1067]], grad_fn=<AddmmBackward>)


In [53]:
net.zero_grad()
print(out)

tensor([[-0.0680,  0.0659, -0.0312, -0.0723,  0.0846,  0.0389,  0.0479, -0.0341,
          0.0756, -0.1067]], grad_fn=<AddmmBackward>)


In [54]:
out.backward(torch.randn(1,10))

In [55]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

torch.Size([1, 16, 6, 6])
tensor(0.6084, grad_fn=<MseLossBackward>)


In [79]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv2.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv2.bias.grad)


conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0141, -0.0055,  0.0021,  0.0040, -0.0052, -0.0121, -0.0009,  0.0000,
        -0.0113,  0.0046,  0.0025,  0.0084,  0.0033,  0.0049, -0.0039, -0.0005])


torch.Size([1, 10])

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms